apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Chart.Name}}-data
spec:
  storageClass: {{.Values.storage.data.storageClass}}
  accessModes: {{.Values.storage.data.accessModes}}
  resources:
    requests:
      storage: {{.Values.storage.data.size}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Chart.Name}}-qbittorrent-config
spec:
  storageClass: {{.Values.storage.configs.storageClass}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.storage.configs.size}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Chart.Name}}-radarr-config
spec:
  storageClass: {{.Values.storage.configs.storageClass}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.storage.configs.size}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Chart.Name}}-sonarr-config
spec:
  storageClass: {{.Values.storage.configs.storageClass}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.storage.configs.size}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Chart.Name}}-prowlarr-config
spec:
  storageClass: {{.Values.storage.configs.storageClass}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.storage.configs.size}}