apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{.Chart.Name}}
  ports:
    - port: {{.Values.config.qbittorrent.port}}
      protocol: TCP
      targetPort: 8080
    - port: {{.Values.config.radarr.port}}
      protocol: TCP
      targetPort: 7878
    - port: {{.Values.config.sonarr.port}}
      protocol: TCP
      targetPort: 8989
    - port: {{.Values.config.prowlarr.port}}
      protocol: TCP
      targetPort: 9696